### ISSUE TITLE
Add $ccls/member feature

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/vscode-ccls#37]
@MaskRay can you describe what does this feature do? Is it another hierarchy?

I think I will create ccls viewlet and move all our treeviews to it.

**Comment by MaskRay** [comment]
The three hierarchies have similar parameters and return types. They are implemented in:

* $ccls/call https://github.com/maskray/ccls/blob/master/src/messages/ccls_call.cc
* $ccls/inheritance https://github.com/maskray/ccls/blob/master/src/messages/ccls_inheritance.cc
* $ccls/member https://github.com/maskray/ccls/blob/master/src/messages/ccls_member.cc

`"$ccls/member"` can be invoked in two ways.

## `hierarchy: false`

Since this is the default, `hierarchy` does not need to be specified explicitly. You may send a request with method `"$ccls/member"` and params `TextDocumentPositionParams`

```
{"jsonrpc":"2.0","id":2,"method":"$ccls/member","params":{"textDocument":{"uri":"file:///tmp/c/a.cc"},"position":{"line":0,"character":7}}}
```

The result is of type `Location[]` (the same as the traditional `textDocument/definition`)

```javascript
{"jsonrpc":"2.0","id":2,"result":[{"uri":"file:///tmp/c/a.cc","range":{"start":{"line":1,"character":6},"end":{"line":1,"character":7}}},{"uri":"file:///tmp/c/a.cc","range":{"start":{"line":2,"character":6},"end":{"line":2,"character":7}}}]}
```

## `hierarchy: true`

Member variables can be further expanded to deeper levels in the hierarchy.

```javascript
{"jsonrpc":"2.0","method":"$ccls/member","params":{"textDocument":{"uri":"file:///tmp/c/a.cc"},"position":{"line":0,"character":7},"levels":1,"qualified":false,"hierarchy":true},"id":457}
```

The return type is of a ccls-specific type resembing the one used in `$ccls/inheritance` and `$ccls/call`. 

```javascript
{"jsonrpc":"2.0","id":457,"result":{"id":"1265876668139249013","name":"A","fieldName":"","location":{"uri":"file:///tmp/c/a.cc","range":{"start":{"line":0,"character":7},"end":{"line":0,"character":8}}},"numChildren":2,"children":[{"id":"65","name":"int","fieldName":" 0 int a","location":{"uri":"file:///tmp/c/a.cc","range":{"start":{"line":1,"character":6},"end":{"line":1,"character":7}}},"numChildren":0,"children":[]},{"id":"65","name":"int","fieldName":" 4 int b","location":{"uri":"file:///tmp/c/a.cc","range":{"start":{"line":2,"character":6},"end":{"line":2,"character":7}}},"numChildren":0,"children":[]}]}}
```

**Comment by Yanpas** [comment]
implemented in master, currently only variable hierarchy is supported as most useful on the daily basis.
