### ISSUE TITLE
 call hierarchy doesn't work if the source code has more than 32768 lines

### ISSUE THREAD

**Issue by Rayaray** [MaskRay/vscode-ccls#46]
the reference link doesn't show correctly if a file has more than 32768 lines, please see attached screenshot:
![image](https://user-images.githubusercontent.com/3817941/52940989-cd15fe80-33a2-11e9-82cc-35d18c5451c2.png)

NOTE: cquery has the same issue.

**Comment by MaskRay** [comment]
The issue is related to the representation of a position, unrelated to vscode-ccls.

https://github.com/maskray/ccls/blob/master/src/position.hh#L24
```cpp
struct Pos {
  int16_t line = -1;
  int16_t column = -1;
};
```

I have the same feeling that this may be rearranged as bit fields. This may happen at some point.

**Comment by rbresalier** [comment]
I'm using a preprocessed file to try and reproduce an issue I'm seeing with ccls, because providing all the dependencies for you to repro the problem would be very difficult.

In this preprocessed file, the line numbers are much larger than 65535. For example, on line 197025 I try to "go to definition", where the definition is on line 196924, but ccls goes to line 65536 in gvim. Then if I do "find references" on line 197025, it says "Not found!".

I think it would be very useful if ccls used 32 bits for line numbers.

Not sure if my original problem is due to only 16 bit line numbers but this seems like a big limitation, especially if users want to provide you with preprocessed files as test cases as that would be much easier.

**Comment by rbresalier** [comment]
Created ccls issue https://github.com/MaskRay/ccls/issues/366 for this
