### ISSUE TITLE
New highlighting configuration in VS Code

### ISSUE THREAD

**Issue by eugnsp** [MaskRay/vscode-ccls#77]
I use(d) different colors for `freeStandingFunctions`, `memberFunctions`, and `staticMemberFunctions`:

```
"ccls.highlighting.colors.freeStandingFunctions": [...],
"ccls.highlighting.colors.memberFunctions": [...],
"ccls.highlighting.colors.staticMemberFunctions": [...],
```

After the last update all my colors are gone. I've read about [new settings](https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code), but I still don't understand how I can get my *different* colors back. The configuration of colors seems to have become much more limited.

**Comment by MaskRay** [comment]
The wiki says

```typescript
"ccls.highlight.function.face": ["enabled"],
"ccls.highlight.type.face": ["enabled"],
"ccls.highlight.variable.face": ["enabled"],
```

works for vscode-ccls>=0.1.28.

The colors are predefined

```
// Predefined by package.json
"ccls.highlight.function.colors": ["#e5b124", "#927754", "#eb992c", "#e2bf8f", "#d67c17", "#88651e", "#e4b953", "#a36526", "#b28927", "#d69855"],
"ccls.highlight.type.colors": ["#e1afc3", "#d533bb", "#9b677f", "#e350b6", "#a04360", "#dd82bc", "#de3864", "#ad3f87", "#dd7a90", "#e0438a"],
"ccls.highlight.variable.colors": ["#587d87", "#26cdca", "#397797", "#57c2cc", "#306b72", "#6cbcdf", "#368896", "#3ea0d2", "#48a5af", "#7ca6b7"],

"ccls.highlight.macro.colors": ["#e79528", "#c5373d", "#e8a272", "#d84f2b", "#a67245", "#e27a33", "#9b4a31", "#b66a1e", "#e27a71", "#cf6d49"],
"ccls.highlight.namespace.colors": ["#429921", "#58c1a4", "#5ec648", "#36815b", "#83c65d", "#417b2f", "#43cc71", "#7eb769", "#58bf89", "#3e9f4a"],
```

**Comment by notskm** [comment]
You misunderstand. We used to be able to use specific colors for very specific kinds of things. It's a lot more general and much less flexible now.

**For example, I used to use these settings:**
* `"ccls.highlighting.colors.globalVariables": ["#D16969"]`
* `"ccls.highlighting.colors.variables": ["#9CDCFE"]`

This resulted in *all* global variables being colored red and *all* non-global variables being colored light blue.

**Now, I have to do this:**
* `"ccls.highlight.variable.colors": ["#9CDCFE"]`

This results in *all* variables, global and non-global being colored light blue. This is *not* what I want. There is no option to use a different color for global variables anymore.

---

I'm going to be frank here. I don't like the new system at all. I find it confusing, unintuitive, and inflexible. I would much prefer if  #75 was reverted.

It looks like the only real reason for #75 was because setting a lot of options was tedious. I strongly disagree. You only have to set the options once. I also much prefer the flexibility and simplicity of the old system.
